#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+TITLE:     Abhijit Paul

* About me
I am Abhijit Paul, a software-engineering student in University of Dhaka. Currently, I am a learner.
I have the following skill set.
1. Expert in c and java
2. Swing and JavaFX and Qt5 for frontend
3. File handling for backend
4. ~Data Science~ using Python (Data Cleaning, Curating, Exploration, Visualization, Feature engineering, Modeling, Machine Learning).

* Is using pc for an extended period of time a bad idea?

It is not. 
** Hardware lifetime is counted in decades
   Unless you plan to use same hardware for more than a decade, running pc for an extended period is not a problem.
** Booting up pc also "harms" pc
The sudden surge of electricity also harms the pc. So many people, in past, used to advocate for not turning off the pc at all.
** Many people runs their pc 24/7
People who want to access files in their home pc from office, usually just keeps the pc running 24/7.
** Power cost
It does cost electricity to keep the pc running. A desktop PC typically uses around 100 watts of electricity, the equivalent of 0.1 unit (about 0.2 unit when loudspeakers and printer included.).

In bangladesh, dhaka, 1 unit is about 7 tk.
So you spend 7tk for 10 hours of pc usage.
* How to get started with emacs?
- Try the basic emacs keybindings
- Its not recommended to immediately start with evil package. However, if you are a vim guy, consider doom-emacs. 
- Tinker around for a month
- Try new packages from various youtube and online channels and choose your own. 

I don't really recommend using someone else configurations and using those packages. If you are already at this stage, consider giving them up and start from scratch. Only this way can you be a emacs user from a emacs newbie - by configuring everything yourself.

