#+TITLE: Free tier of Gemini and other LLMs for you
#+AUTHOR: Abhijit Paul
#+DATE: <2024-08-15 বৃহঃ>

[[https://ai.google.dev/gemini-api/docs/ai-studio-quickstart][google AI studio free 2M tokens]]


"You are a Bangla news article analyzer. I will give you a news article and you will say which genre(s) it belongs to. The genres are:  Politics, Crime, International Affairs,  Business & Economy,  Sports,  Culture & Entertainment,  Jobs,  Lifestyle,  Health,  Environment,  Local news,  Education,  Technology,  Religion,  Science,  Protests and Social Movements, Govt Actions. Additionally, you will also say if the description is Straight, Investigation, Commentary. Return me just a json of {\"genre\": GENRE, \"description_style\": STYLE}.",
          "News article:  আন্তর্জাতিক\n আদিবাসী দিবস উপলক্ষে বুধবার বিভিন্ন স্থানে সভা-সমাবেশ ও রযালি অনুষ্ঠিত \nহয়েছে। উপজাতিদের\n বিভিন্ন সংগঠন এসব কর্মসূচির আয়োজন করে। যুগান্তর ব্যুরো ও প্রতিনিধিদের \nপাঠানো খবর-সিলেট ব্যুরো : রযালিতে সিলেট প্রেস ক্লাবের সভাপতি ইকরামুল \nকবির, ইমজার সভাপতি আল আজাদসহ সিলেটের সাংস্কৃতিক অঙ্গনের ব্যক্তি ও উপজাতি\n জনগোষ্ঠীর লোকজন ছাড়াও বিভিন্ন শ্রেণী-পেশার মানুষ অংশগ্রহণ করেন। এছাড়া \nদিবসটি উপলক্ষে শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়ে আলোচনা সভা \nঅনুষ্ঠিত হয়েছে। ‘অ্যাসোসিয়েশন অব ইন্ডিজেনাস স্টুডেন্টস, সাস্ট’ ও \nসমাজকর্ম বিভাগ আলাদা আলাদাভাবে দিবসটি উপলক্ষে রযালি, সেমিনার ও আলোচনা \nসভার আয়োজন করে।ময়মনসিংহ ব্যুরো : অনুষ্ঠানের উদ্বোধন করেন জেলা পরিষদের \nচেয়ারম্যান অধ্যাপক ইউসুফ খান পাঠান। বক্তব্য রাখেন হিন্দু বৌদ্ধ খ্রিস্টান\n ঐক্য পরিষদের সভাপতি বিকাশ রায়, সিপিবি সভাপতি এমদাদুল হক মিল্লাত, মহিলা \nপরিষদের সভানেত্রী ফেরদৌস আরা মাহমুদা হেলেন, হিল্লুুল নকরেক, অরণ্য-ই \nচিরান, স্বর্ণকান্ত হাজং সাংবাদিক \nশরীফুজ্জামান টিটু প্রমুখ।শেরপুর : বাগাছাস সভাপতি রুনু নকরেটের সভাপতিত্বে\n অনুষ্ঠিত আলোচনা সভায় প্রধান অতিথি ছিলেন ঝিনাইগাতী উপজেলা চেয়ারম্যান \nআমিনুল ইসলাম বাদশা। বক্তব্য রাখেন, উপজেলা ভাইস চেয়ারম্যান আমিরুর ইসলাম \nমক্কু, বাগাছাসের কেন্দ্রীয় কমিটি সাবেক সভাপতি পবিত্র ম্র্রং, সাংবাদিক \nরফিক মজিদ, উপজাতি ছাত্রনেতা নিরু চিরান, \nরবি কোচ, সত্যজিৎ মৃ প্রমুখ।কলমাকান্দা (নেত্রকোনা) : হাটগোবিন্দপুর \nবিদ্যালয় মাঠে অনুষ্ঠানে বক্তব্য রাখেন উপজেলা ভাইস চেয়ারম্যান কলি আক্তার,\n পপি সিডস প্রোগ্রাম ম্যানেজার শরিফুল ইসলাম, টিউলিপ ম্রং, অশোক চিসিম, \nইউলসন কুবি প্রমুখ।দুর্গাপুর (নেত্রকোনা) : রযালি শেষে টিডব্লিউএ’র সভাপতি \nবঙ্কিম মানখিনের সভাপতিত্বে সভায় উপজাতি \nনেতা সায়মন তজুর সঞ্চালনায় প্রধান অতিথি ছিলেন সহকারী কমিশনার ভূমি মো. \nইয়ামিন হোসেন। বক্তব্য রাখেন ভারপ্রাপ্ত পুলিশ কর্মকর্তা মিজানুর রহমান, \nআদিবাসী নারীনেত্রী স্বপ্না হাজং, লুদিয়া রুমা সাংমা, এনজিও সমন্বয় পরিষদের\n সভাপতি মি. পঙ্কজ মারাক, স্বপন হাজং প্রমুখ।শ্রীমঙ্গল : বুধবার রযালি ও \nপথসভার উদ্বোধন করেন বৃহত্তম আদিবাসী ফোরামের সহ-সভাপতি জিডিসন প্রধান \nসুচিয়াং। উপস্থিত ছিলেন সংগঠনের মহাসচিব ফিলা পত্মি, চা জনগোষ্ঠী আদিবাসী\n ফ্রন্টের সভাপতি পরিমল সিং বাড়াইক, খাসি সোসিয়াল কাউন্সিলের সাজু মারছিয়াং\n প্রমুখ।ধোবাউড়া (ময়মনসিংহ) : আলোচনা সভায় বাগাছাস ধোবাউড়া শাখার সভাপতি \nসাগর ডিব্রার সভাপতিত্বে বক্তব্য রাখেন ট্রাইবাল ওয়েলফেয়ার অ্যাসোসিয়েশনের \nচেয়ারম্যান এডুয়ার্ট নাফাক, ভাইস চেয়ারম্যান হেরোথ চিরান, বাগাছাস \nকেন্দ্রীয় প্রচার সম্পাদক শক্তি চিরান, ধোবাউড়া শাখার সম্পাদক ন্যান্সি \nডিব্রা প্রমুখ।কলাপাড়া : সভায় সভাপতিত্ব করেন রাখাইন মংচো।\n প্রধান অতিথির বক্তব্য রাখেন উপজেলা চেয়ারম্যান আবদুল মোতালেব তালুকদার। \nবিশেষ অতিথি ছিলেন ইউএনও এবিএম সাদিকুর রহমান, কৃষি কর্মকর্তা মসিউর রহমান,\n অধ্যক্ষ ড. শহীদুল ইসলাম বিশ্বাস, মাহমুদুর রহমান, সাংবাদিক জসিম পারভেজ, \nরাখাইন চোথেন মং ও অংনয় প্রমুখ।হালুয়াঘাট (ময়মনসিংহ) : গারো\n স্টুডন্ট ইউনিয়ন (গাসু) এবং সেন্টএন্ড্রুজ বয়েজ ও সেন্ট মেরিস গার্লস \nসিএমডি হোস্টেলের নেতারা অংশগ্রহণে একটি রযালি হালুয়াঘাট বাজার প্রদক্ষিণ \nকরে।",
          "Genre: {'genre': ['Culture & Entertainment'],\n'description_style': 'Commentary'}",
          "News article:  বেতন ভাতার দাবিতে ৪৮ ঘণ্টার আলটিমেটাম দিয়েছে হবিগঞ্জের মাধবপুর উপজেলার বৈকুণ্ঠপুর চা বাগানের শ্রমিকরা। রোববার দুপুরে জেলা প্রশাসকের কাছে স্মারকলিপি দেয়ার সময় তারা এ আলটিমেটাম দেয়। বেঁধে দেয়া সময়ের মধ্যে সমাধান না হলে আগামী ১৭ আগস্ট তারা ঢাকা-সিলেট মহাসড়ক অবরোধের হুমকি দেয়। এর আগে চা শ্রমিকরা শহরে বিক্ষোভ মিছিল করে জেলা প্রশাসকের কার্যালয়ের সামনে সমাবেশ করে। মোহন রবিদাসের পরিচালনায় এতে বক্তৃতা করেন চা শ্রমিক ইউনিয়নের উপদেষ্টা কাঞ্চন পাত্র ও নৃপেন পাল। এ সময় বক্তারা জানান গত ৪ মাস ধরে ওই বাগানের চা শ্রমিকরা বেতন ভাতা পাচ্ছেন না। এ সময়ের মধ্যে অনাহারে অর্ধাহারে থেকে নানা রোগে আক্রান্ত হয়ে চিকিৎসার অভাবে তাদের ৭ জন শ্রমিক ও কর্মচারী মারা গেছে। চা শ্রমিক ইউনিয়নের উপদেষ্টা কাঞ্চন পাত্র জানান, গত ৪ মাসে বাগানের টিলা বাবু সাহাদুল ইসলাম, টিলা বাবু মরণ চক্রবর্তী, শ্রমিক সাধন সাঁওতাল, নিতাই সাঁওতাল, নিষ্ণু কেউট, লক্ষ্মী মনি ভূমিজ ও পবন সাঁওতাল মারা গেছেন। ৭ জন মারা যাওয়ার বিষয়টি তিনি অবগত নন জানিয়ে জেলা প্রশাসক সাবিনা আলম জানান, ইতিমধ্যে চা শ্রমিকরদের প্রত্যেক পরিবারকে ২০ কেজি করে চাল দেয়া হয়েছে। এখন আরও ২০ কেজি করে চাল দেয়া হবে। আগে মালিক ওয়াদা করেছিলেন ৪ আগস্ট শ্রমিকদের পেমেন্ট দিয়ে দেবেন। কিন্তু তিনি কথা রাখেননি। বেতন ভাতা না পেয়ে কিছু শ্রমিক দিনমজুর, কেউ অন্য বাগানে গিয়ে কাজ করছে। আবার কিছু শ্রমিক এ বাগানটিকে ধরে রেখেছে। বাগান নষ্ট হতে দেননি। তিনি বলেন, আমি মালিকপক্ষের সঙ্গে কথা বলব। তাদের নোটিশ করব কেন তাদের লিজ বাতিল করা হবে না।",
          "Genre: {'genre': ['Protests and Social Movements', 'Crime'],\n'description_style': 'Investigative'}"
